[package]
name = "keycode_macro"
version = "0.1.0"
authors = ["Dylan Frankland <dfrankland@users.noreply.github.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.2"
proc-macro2 = "1.0.6"
heck = "0.3.1"
anyhow = "1.0.26"

[dev-dependencies]
bitflags = "1.0.4"
